const players = [
    { no: 1, firstname: "Beau", lastname: "Alvarez", pos: "a catcher", image: "images/players/1 Beau Alvarez.png", pr1: "He", pr2: "him",  pr3: "his", pr4: "guy's", pr5: "he's" },
    { no: 2, firstname: "Kyson", lastname: "Frost", pos: "an outfielder", image: "images/players/2 Kyson Frost.png", pr1: "He", pr2: "him",  pr3: "his", pr4: "guy's", pr5: "he's" },
    { no: 3, firstname: "Garret", lastname: "Smink", pos: "a utility player", image: "images/players/3 Garret Smink.png", pr1: "He", pr2: "him",  pr3: "his", pr4: "guy's", pr5: "he's" },
    { no: 4, firstname: "Bryce", lastname: "Ready", pos: "an infielder", image: "images/players/4 Bryce Ready.png", pr1: "He", pr2: "him",  pr3: "his", pr4: "guy's", pr5: "he's" },
    { no: 5, firstname: "KJ", lastname: "DeBarge", pos: "an infielder", image: "images/players/5 KJ DeBarge.png", pr1: "He", pr2: "him",  pr3: "his", pr4: "guy's", pr5: "he's" },
    { no: 6, firstname: "Tanner", lastname: "Swain", pos: "an infielder", image: "images/players/6 Tanner Swain.png", pr1: "He", pr2: "him",  pr3: "his", pr4: "guy's", pr5: "he's" },
    { no: 7, firstname: "Trey", lastname: "Favors", pos: "an infielder", image: "images/players/7 Trey Favors.png", pr1: "He", pr2: "him",  pr3: "his", pr4: "guy's", pr5: "he's" },
    { no: 8, firstname: "Tatsunori", lastname: "Schmidt", pos: "a utility player", image: "images/players/8 Tatsunori Schmidt.png", pr1: "He", pr2: "him",  pr3: "his", pr4: "guy's", pr5: "he's" },
    { no: 9, firstname: "Walker", lastname: "Mendez", pos: "an infielder", image: "images/players/9 Walker Mendez.png", pr1: "He", pr2: "him",  pr3: "his", pr4: "guy's", pr5: "he's" },
    { no: 10, firstname: "Clyde", lastname: "Babee", pos: "a pitcher", image: "images/players/10 Clyde Babee.png", pr1: "He", pr2: "him",  pr3: "his", pr4: "guy's", pr5: "he's" },
    { no: 11, firstname: "Khal", lastname: "Valdez", pos: "a pitcher", image: "images/players/11 Khal Valdez.png", pr1: "He", pr2: "him",  pr3: "his", pr4: "guy's", pr5: "he's" },
    { no: 12, firstname: "Tressa", lastname: "Scar", pos: "an outfielder", image: "images/players/12 Tressa Scar.png", pr1: "She", pr2: "her",  pr3: "her", pr4: "gal's", pr5: "she's" },
    { no: 13, firstname: "Reese", lastname: "Witherspoon", pos: "a pitcher", image: "images/players/13 Reese Witherspoon.png", pr1: "He", pr2: "him",  pr3: "his", pr4: "guy's", pr5: "he's" },
    { no: 14, firstname: "RJ", lastname: "Zimbardo", pos: "a catcher", image: "images/players/14 RJ Zimbardo.png", pr1: "He", pr2: "him",  pr3: "his", pr4: "guy's", pr5: "he's" },
    { no: 15, firstname: "Dalton", lastname: "Seeker", pos: "an outfielder", image: "images/players/15 Dalton Seeker.png", pr1: "He", pr2: "him",  pr3: "his", pr4: "guy's", pr5: "he's" },
    { no: 16, firstname: "Dean", lastname: "Devine", pos: "a pitcher", image: "images/players/16 Dean Devine.png", pr1: "He", pr2: "him",  pr3: "his", pr4: "guy's", pr5: "he's" },
    { no: 17, firstname: "Griffin", lastname: "Kuntz", pos: "a pitcher", image: "images/players/17 Griffin Kuntz.png", pr1: "He", pr2: "him",  pr3: "his", pr4: "guy's", pr5: "he's" },
    { no: 18, firstname: "Clayton", lastname: "Krauss", pos: "a pitcher", image: "images/players/18 Clayton Krauss.png", pr1: "He", pr2: "him",  pr3: "his", pr4: "guy's", pr5: "he's" },
    { no: 19, firstname: "Blake", lastname: "Blanco", pos: "an outfielder", image: "images/players/19 Blake Blanco.png", pr1: "He", pr2: "him",  pr3: "his", pr4: "guy's", pr5: "he's" },
    { no: 20, firstname: "Yorks", lastname: "Font", pos: "an outfielder", image: "images/players/20 Yorks Font.png", pr1: "He", pr2: "him",  pr3: "his", pr4: "guy's", pr5: "he's" },
    { no: 21, firstname: "Carter", lastname: "Sass", pos: "an outfielder", image: "images/players/21 Carter Sass.png", pr1: "He", pr2: "him",  pr3: "his", pr4: "guy's", pr5: "he's" },
    { no: 22, firstname: "Michael", lastname: "Vu", pos: "a pitcher", image: "images/players/22 Michael Vu.png", pr1: "He", pr2: "him",  pr3: "his", pr4: "guy's", pr5: "he's" },
    { no: 23, firstname: "Tyler", lastname: "Quinlan", pos: "an outfielder", image: "images/players/23 Tyler Quinlan.png", pr1: "He", pr2: "him",  pr3: "his", pr4: "guy's", pr5: "he's" },
    { no: 24, firstname: "Jordan", lastname: "Mallory Jr.", pos: "an outfielder", image: "images/players/24 Jordan Mallory Jr.png", pr1: "He", pr2: "him",  pr3: "his", pr4: "guy's", pr5: "he's" },
    { no: 25, firstname: "Aaron", lastname: "Toole", pos: "a pitcher", image: "images/players/25 Aaron Toole.png", pr1: "He", pr2: "him",  pr3: "his", pr4: "guy's", pr5: "he's" },
    { no: 26, firstname: "Kellen", lastname: "Mercer", pos: "a pitcher", image: "images/players/26 Kellen Mercer.png", pr1: "He", pr2: "him",  pr3: "his", pr4: "guy's", pr5: "he's" },
    { no: 27, firstname: "Nick", lastname: "Driscoll", pos: "a pitcher", image: "images/players/27 Nick Driscoll.png", pr1: "He", pr2: "him",  pr3: "his", pr4: "guy's", pr5: "he's" },
    { no: 28, firstname: "Kenneth", lastname: "Couture", pos: "a pitcher", image: "images/players/28 Kenneth Couture.png", pr1: "He", pr2: "him",  pr3: "his", pr4: "guy's", pr5: "he's" },
    { no: 29, firstname: "Niko", lastname: "Serrano", pos: "an infielder", image: "images/players/29 Niko Serrano.png", pr1: "He", pr2: "him",  pr3: "his", pr4: "guy's", pr5: "he's" },
    { no: 30, firstname: "Kermit", lastname: "Grastan", pos: "a utility player", image: "images/players/30 Kermit Grastan.png", pr1: "He", pr2: "him",  pr3: "his", pr4: "guy's", pr5: "he's" },
    { no: 31, firstname: "Chris", lastname: "McCrystal", pos: "a pitcher", image: "images/players/31 Chris McCrystal.png", pr1: "He", pr2: "him",  pr3: "his", pr4: "guy's", pr5: "he's" },
    { no: 32, firstname: "Jurrangelo", lastname: "Kryszczuk", pos: "a pitcher", image: "images/players/32 Jurrangelo Kryszczuk.png", pr1: "He", pr2: "him",  pr3: "his", pr4: "guy's", pr5: "he's" },
    { no: 33, firstname: "Mitch", lastname: "Grinsell", pos: "a catcher", image: "images/players/33 Mitch Grinsell.png", pr1: "He", pr2: "him",  pr3: "his", pr4: "guy's", pr5: "he's" },
    { no: 34, firstname: "Matt", lastname: "Pennington", pos: "an infielder", image: "images/players/34 Matt Pennington.png", pr1: "He", pr2: "him",  pr3: "his", pr4: "guy's", pr5: "he's" },
    { no: 35, firstname: "Linzora", lastname: "Shatzman", pos: "a pitcher", image: "images/players/35 Linzora Shatzman.png", pr1: "She", pr2: "her",  pr3: "her", pr4: "gal's", pr5: "she's" },
    { no: 36, firstname: "Dom", lastname: "Compton", pos: "a pitcher", image: "images/players/36 Dom Compton.png", pr1: "He", pr2: "him",  pr3: "his", pr4: "guy's", pr5: "he's" },
    { no: 37, firstname: "Melvin", lastname: "Carroule", pos: "a catcher", image: "images/players/37 Melvin Carroule.png", pr1: "He", pr2: "him",  pr3: "his", pr4: "guy's", pr5: "he's" },
    { no: 38, firstname: "Luke", lastname: "Pooser", pos: "a pitcher", image: "images/players/38 Luke Pooser.png", pr1: "He", pr2: "him",  pr3: "his", pr4: "guy's", pr5: "he's" },
    { no: 39, firstname: "Travis", lastname: "Desandro", pos: "a first baseman", image: "images/players/39 Travis Desandro.png", pr1: "He", pr2: "him",  pr3: "his", pr4: "guy's", pr5: "he's" },
    { no: 40, firstname: "Leighton", lastname: "D'Amato", pos: "an infielder", image: "images/players/40 Leighton D'Amato.png", pr1: "He", pr2: "him",  pr3: "his", pr4: "guy's", pr5: "he's" },
    { no: 41, firstname: "Maina", lastname: "Dogsta", pos: "a first baseman", image: "images/players/41 Maina Dogsta.png", pr1: "She", pr2: "her",  pr3: "her", pr4: "gal's", pr5: "she's" },
    { no: 43, firstname: "Brent", lastname: "Tracer", pos: "a pitcher", image: "images/players/43 Brent Tracer.png", pr1: "He", pr2: "him",  pr3: "his", pr4: "guy's", pr5: "he's" },
    { no: 44, firstname: "Donnisa", lastname: "Chilsick", pos: "a pitcher", image: "images/players/44 Donnisa Chilsick.png", pr1: "She", pr2: "her",  pr3: "her", pr4: "gal's", pr5: "she's" },
    { no: 45, firstname: "Elmo", lastname: "Stich", pos: "an infielder", image: "images/players/45 Elmo Stich.png", pr1: "He", pr2: "him",  pr3: "his", pr4: "guy's", pr5: "he's" },
    { no: 47, firstname: "Reed", lastname: "Clonne", pos: "an outfielder", image: "images/players/47 Reed Clonne.png", pr1: "She", pr2: "her",  pr3: "her", pr4: "gal's", pr5: "she's" },
    { no: 48, firstname: "Mony", lastname: "Coblas", pos: "a pitcher", image: "images/players/48 Mony Coblas.png", pr1: "She", pr2: "her",  pr3: "her", pr4: "gal's", pr5: "she's" },
    { no: 49, firstname: "Whres", lastname: "Eet", pos: "an infielder", image: "images/players/49 Whres Eet.png", pr1: "They", pr2: "them",  pr3: "their", pr4: "person's", pr5: "they're" },
    { no: 51, firstname: "Lanny", lastname: "Mandon", pos: "a catcher", image: "images/players/51 Lanny Mandon.png", pr1: "She", pr2: "her",  pr3: "her", pr4: "gal's", pr5: "she's" },
    { no: 52, firstname: "Leona", lastname: "Rotor", pos: "a pitcher", image: "images/players/52 Leona Rotor.png", pr1: "She", pr2: "her",  pr3: "her", pr4: "gal's", pr5: "she's" },
    { no: 53, firstname: "Laren", lastname: "Pyton", pos: "a utility player", image: "images/players/53 Laren Pyton.png", pr1: "She", pr2: "her",  pr3: "her", pr4: "gal's", pr5: "she's" },
    { no: 54, firstname: "Cassio", lastname: "Farrane", pos: "a pitcher", image: "images/players/54 Cassio Farrane.png", pr1: "He", pr2: "him",  pr3: "his", pr4: "guy's", pr5: "he's" },
    { no: 55, firstname: "Nilo", lastname: "Socc", pos: "an infielder", image: "images/players/55 Nilo Socc.png", pr1: "He", pr2: "him",  pr3: "his", pr4: "guy's", pr5: "he's" },
    { no: 57, firstname: "Mavis", lastname: "Shen", pos: "an outfielder", image: "images/players/57 Mavis Shen.png", pr1: "She", pr2: "her",  pr3: "her", pr4: "gal's", pr5: "she's" },
    { no: 60, firstname: "Warren", lastname: "Saint", pos: "an infielder", image: "images/players/60 Warren Saint.png", pr1: "He", pr2: "him",  pr3: "his", pr4: "guy's", pr5: "he's" },
    { no: 62, firstname: "Reneck", lastname: "Mellet", pos: "a pitcher", image: "images/players/62 Reneck Mellet.png", pr1: "He", pr2: "him",  pr3: "his", pr4: "guy's", pr5: "he's" },
    { no: 63, firstname: "Ebolda", lastname: "Huntin", pos: "an infielder", image: "images/players/63 Ebolda Huntin.png", pr1: "She", pr2: "her",  pr3: "her", pr4: "gal's", pr5: "she's" },
    { no: 66, firstname: "Dante", lastname: "Info", pos: "a catcher", image: "images/players/66 Dante Info.png", pr1: "He", pr2: "him",  pr3: "his", pr4: "guy's", pr5: "he's" },
    { no: 67, firstname: "Wren", lastname: "Pagon", pos: "an infielder", image: "images/players/67 Wren Pagon.png", pr1: "She", pr2: "her",  pr3: "her", pr4: "gal's", pr5: "she's" },
    { no: 69, firstname: "Cumnong", lastname: "Hamdic", pos: "an infielder", image: "images/players/69 Cumnong Hamdic.png", pr1: "He", pr2: "him",  pr3: "his", pr4: "guy's", pr5: "he's" },
    { no: 71, firstname: "Luffin", lastname: "Grikintz", pos: "a pitcher", image: "images/players/71 Luffin Grikintz.png", pr1: "He", pr2: "him",  pr3: "his", pr4: "guy's", pr5: "he's" },
    { no: 75, firstname: "Lexy", lastname: "Adnhea", pos: "an outfielder", image: "images/players/75 Lexy Adnhea.png", pr1: "She", pr2: "her",  pr3: "her", pr4: "gal's", pr5: "she's" },
    { no: 77, firstname: "Coin", lastname: "Klank", pos: "a pitcher", image: "images/players/77 Coin Klank.png", pr1: "He", pr2: "him",  pr3: "his", pr4: "guy's", pr5: "he's" },
    { no: 78, firstname: "Jolka", lastname: "Bot", pos: "a pitcher", image: "images/players/78 Jolka Bot.png", pr1: "She", pr2: "her",  pr3: "her", pr4: "gal's", pr5: "she's" },
    { no: 82, firstname: "Tucketh", lastname: "Norene", pos: "a pitcher", image: "images/players/82 Tucketh Norene.png", pr1: "He", pr2: "him",  pr3: "his", pr4: "guy's", pr5: "he's" },
    { no: 84, firstname: "Blon", lastname: "Narkel", pos: "a pitcher", image: "images/players/84 Blon Narkel.png", pr1: "She", pr2: "her",  pr3: "her", pr4: "gal's", pr5: "she's" },
    { no: 88, firstname: "Nutpuck", lastname: "Minimick", pos: "a pitcher", image: "images/players/88 Nutpuck Minimick.png", pr1: "He", pr2: "him",  pr3: "his", pr4: "guy's", pr5: "he's" },
    { no: 92, firstname: "Rokie", lastname: "Sarnon", pos: "an infielder", image: "images/players/92 Rokie Sarnon.png", pr1: "She", pr2: "her",  pr3: "her", pr4: "gal's", pr5: "she's" },
    { no: 99, firstname: "Yonk", lastname: "Ribell", pos: "an outfielder", image: "images/players/99 Yonk Ribell.png", pr1: "He", pr2: "him",  pr3: "his", pr4: "guy's", pr5: "he's" },
];